project:
  type: website
  output-dir: docs

website:
  title:  project01-team-holiday

  navbar:
    right:
      - icon: github
        href: https://github.com/math241s24/project01-team-holiday/tree/main
    left:
      - text: Project
        href: index.qmd
      - text: "Proposal"
        href: proposal.qmd
      - text: "Presentation"
        href: presentation.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto