---
title: "Project Proposal"
format: html
editor: visual
---

# Team Holiday Proposal:

Your proposal should include:

-   A brief description of your dataset including its provenance, dimensions, etc. (Make sure to load the data and use inline code for some of this information.)
-   The reason why you chose this dataset.
-   The two questions you want to answer.
    -   A plan for answering each of the questions including the variables involved, variables to be created (if any), external data to be merged in (if any).

**Brief Description:**

[Our data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-12-12/readme.md) is from the Tidy Tuesday dataset with dimensions of 2265x14.

```{r}
library(readr)
library(dplyr)
holiday_movies <- read_csv("data/holiday_movies.csv")
glimpse(holiday_movies)
```

**Why we chose our dataset**

We chose this dataset because we are interested in investigating the relationship between movie types and public reception of them, as well as changes in movie style over time. We wondered whether the holiday the movies were written for played a role in this, i.e. do Christmas movies fare better than Hanukkah movies? 

**Questions:**

1: How does type of holiday affect a movie's rating, and for each holiday, how does the movie's age affect its rating?

2: How do movie run times vary over time? Have holiday movies gotten longer over time? Shorter? Is there a significant difference of run time over time? 

**Plan:** Within our dataset, we will be working with the following variables:

-   primary_title - the most popular title the movie is known by

-   year - the year the movie was released

-   runtime_minutes - the length of the movie, in minutes

-   christmas - whether or not the title contains "christmas" or some variation

-   hanukkah - whether or not the title contains "hanukkah" or some variation

-   kwanzaa - whether or not the title contains "kwanzaa" or some variation

-   holiday - whether or not the title contains "holiday"

-   average_rating - the average rating of the film

To answer our first question, we would start by combining the holidays into one column using a pivot_longer function. Then we could compare the different factors, making visualizations and examining summary statistics. We could even use the facet_wrap function to compare the 3 holidays. We will be using a scatter plot with average_rating on the y-axis, year on the x-axis, and holiday as the color of the points. We may also make a bar graph with holiday on the x-axis and average_rating on the y-axis.

For our second question the data would be clean, having already wrangled it for the first question. We would make a scatter plot with year on the x-axis and run_time on the y-axis, even linking color to the holiday! We may also add a line of best fit to each of the holidays depending on how the graph ends up looking, and whether or not there is a clear trend.
